
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITH_CURRENT_SHELL: "nix-shell --run"


    strategy:
      matrix:
        py:
          - 3.9.9

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install nix dependencies
      run: $WITH_CURRENT_SHELL 'env'

    - name: Make configure script
      run: $WITH_CURRENT_SHELL 'make -C build VERSION=${{matrix.py}}'
